processor-toolbox:
    processors:
      - type: egg-processor
        name: egg
      - type: forward-fftw
        name: fft
      - type: convert-to-power
        name: to-ps
      - type: basic-root-writer
        name: writer

    connections:
      - signal: "egg:header"
        slot: "fft:header"
      - signal: "egg:ts"
        slot: "fft:ts-fftw"
      - signal: "fft:fft"
        slot: "to-ps:fs-fftw-to-psd"
      - signal: "to-ps:psd"
        slot: "writer:ps"

    run-queue:
      - egg

egg:
    filename: "../Project8_Data/test_kr_0_01-03-17_eth1.egg"
    egg-reader: egg3
    slice-size: 16384
    number-of-slices: 1

fft:
    transform-flag: ESTIMATE

writer:
    output-file: "../Project8_Data/test_kr_0_01-03-17_eth1.root"
    file-flag: recreate
