processor-toolbox:
    processors:
      - type: egg-processor
        name: egg
      - type: forward-fftw
        name: fft
      - type: channel-aggregator
        name: ch-sum
      - type: channelsum-optimizer
        name: ch-opt
      - type: convert-to-power
        name: to-ps
      - type: basic-root-writer
        name: writer
      - type: root-spectrogram-writer
        name: waterfall-writer


    connections:
      - signal: "egg:header"
        slot: "fft:header"
      - signal: "egg:ts"
        slot: "fft:ts-fftw"
      - signal: "fft:fft"
        slot: "ch-sum:fft"
      - signal: "ch-sum:fft"
        slot: "ch-opt:fft"
      - signal: "ch-sum:fft"
        slot: "to-ps:aggfs-fftw-to-ps"
      - signal: "ch-sum:fft"
        slot: "writer:agg-fs-fftw"
      - signal: "to-ps:ps"
        slot: "writer:agg-ps"


    run-queue:
      - egg

egg:
    filename: "locust_mc_0.5e-3s_Seed55_LO25.8781G.egg"
    egg-reader: egg3
    slice-size: 8192
    number-of-slices: 10
    stride: 8192

fft:
    transform-flag: ESTIMATE

ch-sum:
    grid-size: 5
    active-radius: 0.0516
    wavelength: 0.011

writer:
    output-file: "Summed_Channels_Test.root"
    file-flag: recreate