processor-toolbox:
    processors:
      - type: egg-processor
        name: egg
      - type: forward-fftw
        name: fft
      - type: image-writer
        name: writer

    connections:
      - signal: "egg:header"
        slot: "fft:header"
      - signal: "egg:ts"
        slot: "fft:ts-fftw"
      - signal: "fft:fft"
        slot: "writer:fs-fftw"
      - signal: "egg:egg-done"
        slot: "writer:write-files"

    run-queue:
      - egg

egg:
    filename: test_input.egg
    egg-reader: egg3
    slice-size: 4096
    number-of-slices: 0

fft:
    transform-flag: ESTIMATE

writer:
    filename-base: test_output
    file-extension: png
    min-time: 0.0
    max-time: 1.0
    min-freq: 0.0
    max-freq: 100.0e6